### ISSUE TITLE
dbの選定

### ISSUE THREAD

**Issue by palloc** [n0stack/n0core#1]
VM情報の保持用dbが必要

**Comment by h-otter** [comment]
以下の点について @palloc などが検証する

- JanusGraphとneo4jの比較検討
- リソーススケジューリングに使えるか否か

**Comment by h-otter** [comment]
適宜repositoryに必要な実装に合わせて考えていく

v0.0.2現在では非常に必要な機能が少ないので実装コストを重視し、memcachedで実装を行う
