### ISSUE TITLE
分散 DHCP の実装方法

### ISSUE THREAD

**Issue by Kurorororo** [n0stack/n0core#15]
# 分散 DHCP について
 
分散 DHCP をどう実装するか検討する必要がある。
基本的には各コンピュートホスト内に DHCP サーバがあり、 VM は同じホスト上の DHCP サーバから IP を割り当てられるようにしたい。

## 同一 IP 方式
各 DHCP サーバの IP アドレスを同一のものにする。

### メリット
- DHCP サーバのために消費する IP アドレスが 1 つしかない。

### デメリット
- ホスト内外の ARP ないし MAC テーブルが汚染されないように ARP 及び GARP パケットがホストから出ないようにする必要がある。
- 上記のデメリット解消にホスト内での `ebtables` の使用が予想される。この場合 OpenStack で発生するような不本意なパケットの DROP が発生し、運用者がめんどくさいことになる可能性がある。

## 個別 IP 方式
各 DHCP サーバの IP アドレスを別々のものにする。

### メリット
- 実装がシンプルである。
- dnsmasq のいる netns 内だけで iptables や ebtables を書けばいいので不本意な DROP は発生しにくい。

### デメリット
- IP アドレスがホストの数だけ消費されるのでサブネットに立てることのできる VM が減ってしまう。

**Comment by h-otter** [comment]
`enable_dhcp: true` であれば外部と内部のDHCPを完全にiptablesで分割

`enable_dhcp: false` の場合はそれらを破棄

そうすることでdhcpがonのときは外部の攻撃に耐えられるが、falseのときは内部に任意のDHCPサーバをたてることもできるので問題作成の制約にならない

**Comment by h-otter** [comment]
- リソースの使用量が見積もりにくい
- リソースの無駄が多い
- 障害ポイントがふえる

よってクラウド基盤としては悪手
